### ISSUE TITLE
Unable to return array from contract

### ISSUE THREAD

**Issue by somak12** [hyperledger/burrow#258] opened 2016-09-06 10:04 UTC
Hi,
I have a simple contract which returns few arrays. Works fine in the online solidity compiler. But after deploying it to the chain and invoking it from the app.js its giving the following error. 

Have found a bug related to this https://github.com/eris-ltd/eris-db.js/issues/27

Any particular reason why this error is occurring?  

My contract is like: 
```javascript
function getMarket() constant returns(uint[], uint[], uint[], uint[]) {
    uint[] memory optionIDs = new uint[](20);
    uint[] memory strikes_ = new uint[](20);
    uint[] memory positions_ = new uint[](20);
    uint[] memory cashes = new uint[](20);
    uint z = 0;
      for (uint i=0; i<10; i++) {
        optionIDs[i] = i;
        strikes_[i] = i+10;
        positions_[i] = i+100;
        cashes[i] = i+50;
        z++;
      }
    return (optionIDs, strikes_, positions_, cashes);
  }
```

Error is:
```
[JSON RPC 2.0 Error] Message Id: 1, (INTERNAL_ERROR) - Error when transacting: Memory out of bounds
[Error: Error when transacting: Memory out of bounds]
Error callback from sendTransaction

/home/azureuser/.eris/apps/test/app.js:50
    if (error) { throw error; }
                       ^
Error: Error when transacting: Memory out of bounds
    at /home/azureuser/.eris/apps/test/node_modules/eris-contracts/node_modules/eris-db/lib/rpc/http.js:79:22
    at httpRequest.onreadystatechange (/home/azureuser/.eris/apps/test/node_modules/eris-contracts/node_modules/eris-db/lib/rpc/http.js:103:17)
    at dispatchEvent (/home/azureuser/.eris/apps/test/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:572:25)
    at setState (/home/azureuser/.eris/apps/test/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:14)
    at IncomingMessage.<anonymous> (/home/azureuser/.eris/apps/test/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:431:13)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by somak12** [comment] 2016-09-06 10:08
Eris version :  0.11.4
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64

**Comment by silasdavis** [comment] 2017-05-09 13:36
Sorry for the delay @somak12, I have looked into this issue and it relates to how solidity stores the array length. I'm going to consolidate this ticket into https://github.com/hyperledger/burrow/issues/413. 

I have a fix in hand, please see there for further discussion.

**Comment by silasdavis** [comment] 2017-05-10 11:11
I was a bit hasty to close this. I'm going to verify that your code works. Would you mind if I used it to make test case in monax/cli?

**Comment by silasdavis** [comment] 2017-05-10 15:59
@somak12 so having looked into this, the initialisation-time dynamic memory arrays (size is a parameter you pass the constructor at runtime) are not yet supported by the EVM. The issue there is that  As you correctly point out on remix (browser solidity) it does work, and I am told this is implemented as something as a work-around in web3 that uses internal knowledge of then state to allow for dynamic array returns.

The problem is that when you make a `CALL` you have to specify the return position and size in memory, see here: https://github.com/ethereum/solidity/issues/164. So there is not a general solution in Solidity. However there is a proposal to provide a mechanism in Ethereum to do this more efficiently via two new opcodes see: https://github.com/ethereum/EIPs/pull/211

In the meantime, the following will work (will return the arrays) (I have been trying this against #607):

```javascript
    function getMarket() constant returns(uint[20], uint[20], uint[20], uint[20]){
        uint[20] memory optionIDs;
        uint[20] memory strikes_;
        uint[20] memory positions_;
        uint[20] memory cashes;
        uint z = 0;
          for (uint i=0; i<10; i++) {
            optionIDs[i] = i;
            strikes_[i] = i+10;
            positions_[i] = i+100;
            cashes[i] = i+50;
            z++;
          }
        return (optionIDs, strikes_, positions_, cashes);
      }
```

If you want to use dynamic arrays internally (as in without returning those values) then you will be able to do so after #607 is merged.

**Comment by somak12** [comment] 2017-07-06 06:58
:)

**Closed** 2018-03-03 11:08 UTC
Labels: bug/confirmed, triaged
