### ISSUE TITLE
[question] chain connection error

### ISSUE THREAD

**Issue by anume1234** [hyperledger/burrow#919] opened 2018-09-23 09:38 UTC
- [ ] `burrow version` (docker image tag or branch if built from source):- 0.21.0
[ ] `monax version` (if applicable) 
- [ ] `go version` (if applicable)g 1.11fi
- [ ] `docker version` (if applicable) 18.06.1-ce
- [ ] operating system details (osx/windows/linux) Ubuntu 16.04 64-bit
- [ ] burrow deploy --address=F71831847564B7008AD30DD56336D9C42787CF63
- [ ] could not connect to server
gave error as following:
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10997: connect: connection refused"

**Comment by compleatang** [comment] 2018-09-25 10:51
@anume1234 can you give us more context on what the issue is here? did you have a chain running before doing the `burrow deploy` ?

**Comment by compleatang** [comment] 2018-10-09 21:38
am closing this issue. feel free to reopen if there is an actual problem here or visit with the community int he #burrow room at chat.hyperledger.org

**Closed by compleatang** 2018-10-09 21:38 UTC
Labels: triaged/response needed
